FROM php:8.5-cli@sha256:5749d0780f2d0c993a63b4eac18501f74d2ca8735aeb97d7fd7c8efb7b9b7467

RUN apt-get update -q \
	&& apt-get install -y -q --no-install-recommends \
		subversion \
		default-mysql-client \
		curl \
		unzip \
		git \
	&& docker-php-ext-install mysqli \
	&& curl -sS https://getcomposer.org/installer \
		| php -- --install-dir=/usr/local/bin --filename=composer \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app
