FROM php:8.5-cli@sha256:1954ff5cd21f222c992b79d25e403b2600cec829678d5bb7076883f3a44c0d6e

RUN apt-get update -q \
	&& apt-get install -y -q --no-install-recommends \
		subversion \
		default-mysql-client \
		curl \
		unzip \
		git \
	&& docker-php-ext-install mysqli \
	&& curl -sS https://getcomposer.org/installer \
		| php -- --install-dir=/usr/local/bin --filename=composer \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app
