FROM php:8.5-cli@sha256:54d82ff9be6bd198145e90c917fc9b2e24230b42e52def8deb3554baf61c451a

RUN apt-get update -q \
	&& apt-get install -y -q --no-install-recommends \
		subversion \
		default-mysql-client \
		curl \
		unzip \
		git \
	&& docker-php-ext-install mysqli \
	&& curl -sS https://getcomposer.org/installer \
		| php -- --install-dir=/usr/local/bin --filename=composer \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app
